# Generated by Django 2.2.5 on 2019-10-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='testimonalCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('cardTitle', models.TextField()),
                ('testimonalContent', models.TextField()),
            ],
        ),
    ]
