# Generated by Django 2.2.5 on 2019-10-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_testimonalcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonalcard',
            name='imageUrl',
            field=models.ImageField(default='xyz', upload_to=''),
        ),
    ]
