# Generated by Django 2.2.5 on 2019-11-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arthroscope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('product', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Hysteroscopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('product', models.TextField()),
            ],
        ),
    ]
