# Generated by Django 2.2.5 on 2019-11-13 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_arthroscope_hysteroscopy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Arthroscope',
            new_name='Arthroscopy',
        ),
    ]
